spring.application.name=CursoSpringBoot_video_18

server.port=8090

# Configuración de MySQL
spring.datasource.url=jdbc:mysql://localhost/laboratorio
spring.datasource.username=springboot
spring.datasource.password=canzervero
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

##Configuracion de la base de datos postgresql
#spring.datasource.url=jdbc:postgresql://localhost:5432/laboratorio
#spring.datasource.username=springboot
#spring.datasource.password=cuervo
#spring.datasource.driver-class-name=org.postgresql.Driver


# Configuración JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


