spring.application.name=CursoSpringBoot_video_12
server.port=8090

#Sirve para desactivar devTools
spring.devtools.restart.enabled=true

#Propiedades asociadas al actuator
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.include=health,env.beans

management.enpoint.health.show-details=always

#Posibles valores para mostrar la informacion de env
#   always, never y when-autorized
management.endpoint.env.show-values=always

management.info.env.enabled=true
info.app.name=CursoSpringBoot_video_12
info.app.versio=1.0.0
info.app.description=Aplicacion que muestra el uso de JPA con PostgreSQL

#Configuracion de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/laboratorio
spring.datasource.username=springboot
spring.datasource.password=cuervo
spring.driver-class-name=org.postgresql.Driver

#Configuracion de JPA/HIbernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
