spring.application.name=CursoSpringBoot_video_11
server.port=8090

#Sirve para desactivar devTools
spring.devtools.restart.enabled=true

# Propiedades asociadas al actuator
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.include=health,env,beans

management.endpoint.health.show-details=always

# Posibles valores para mostrar la informacionde env
#   always, never y when-autorized
management.endpoint.env.show-values=always

management.info.env.enabled=true
info.app.name=CursoSpringBoot_video_11
info.ap.version=1.0.0
info.app.description=Aplicacion que muestra el uso de las dependencias DevTools y Actuator
